//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class studentinfo {
    
    private studentinfoStudentinfo[] studentinfo1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("studentinfo")]
    public studentinfoStudentinfo[] studentinfo1 {
        get {
            return this.studentinfo1Field;
        }
        set {
            this.studentinfo1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class studentinfoStudentinfo {
    
    private string admissionIdField;
    
    private string admissionYearField;
    
    private string studentClassField;
    
    private string studentSectionField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string genderField;
    
    private string dateOfAdmissionField;
    
    private string poBField;
    
    private string dOBField;
    
    private int ageField;
    
    private string motherTongueField;
    
    private string identityMark1Field;
    
    private string identityMark2Field;
    
    private string casteField;
    
    private string physicallyChallengedField;
    
    private string previousClasasYearField;

    private string photoField;
    
    private string busFacilityField;
    
    private string previousSchoolField;
    
    private string prevSchoolAddrField;
    
    private string fatherNameField;
    
    private string motherNameField;
    
    private string emailField;
    
    private string fatherOccupationField;
    
    private string motherOccupationField;
    
    private string nationalityField;
    
    private string religionField;
    
    private string fatherIncomeField;
    
    private string addressField;
    
    private int stateField;

    private int cityField;

    private int distictField;
    
    private string pinCodeField;
    
    private string contactNoField;
    
    private string hostCodeField;
    
    private string statusField;
    
    private int sortSeqField;
    
    private string createdDateField;
    
    private int createdByField;
    
    private string modifiedDateField;
    
    private int modifiedByField;
    
    /// <remarks/>
    public string AdmissionId {
        get {
            return this.admissionIdField;
        }
        set {
            this.admissionIdField = value;
        }
    }
    
    /// <remarks/>
    public string AdmissionYear {
        get {
            return this.admissionYearField;
        }
        set {
            this.admissionYearField = value;
        }
    }
    
    /// <remarks/>
    public string StudentClass {
        get {
            return this.studentClassField;
        }
        set {
            this.studentClassField = value;
        }
    }
    
    /// <remarks/>
    public string StudentSection {
        get {
            return this.studentSectionField;
        }
        set {
            this.studentSectionField = value;
        }
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public string DateOfAdmission {
        get {
            return this.dateOfAdmissionField;
        }
        set {
            this.dateOfAdmissionField = value;
        }
    }
    
    /// <remarks/>
    public string PoB {
        get {
            return this.poBField;
        }
        set {
            this.poBField = value;
        }
    }
    
    /// <remarks/>
    public string DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    public int Age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
    
    /// <remarks/>
    public string MotherTongue {
        get {
            return this.motherTongueField;
        }
        set {
            this.motherTongueField = value;
        }
    }
    
    /// <remarks/>
    public string IdentityMark1 {
        get {
            return this.identityMark1Field;
        }
        set {
            this.identityMark1Field = value;
        }
    }
    
    /// <remarks/>
    public string IdentityMark2 {
        get {
            return this.identityMark2Field;
        }
        set {
            this.identityMark2Field = value;
        }
    }
    
    /// <remarks/>
    public string Caste {
        get {
            return this.casteField;
        }
        set {
            this.casteField = value;
        }
    }
    
    /// <remarks/>
    public string PhysicallyChallenged {
        get {
            return this.physicallyChallengedField;
        }
        set {
            this.physicallyChallengedField = value;
        }
    }
    
    /// <remarks/>
    public string PreviousClasasYear {
        get {
            return this.previousClasasYearField;
        }
        set {
            this.previousClasasYearField = value;
        }
    }
    
    /// <remarks/>
    public string Photo {
        get {
            return this.photoField;
        }
        set {
            this.photoField = value;
        }
    }
    
    /// <remarks/>
    public string BusFacility {
        get {
            return this.busFacilityField;
        }
        set {
            this.busFacilityField = value;
        }
    }
    
    /// <remarks/>
    public string PreviousSchool {
        get {
            return this.previousSchoolField;
        }
        set {
            this.previousSchoolField = value;
        }
    }
    
    /// <remarks/>
    public string PrevSchoolAddr {
        get {
            return this.prevSchoolAddrField;
        }
        set {
            this.prevSchoolAddrField = value;
        }
    }
    
    /// <remarks/>
    public string FatherName {
        get {
            return this.fatherNameField;
        }
        set {
            this.fatherNameField = value;
        }
    }
    
    /// <remarks/>
    public string MotherName {
        get {
            return this.motherNameField;
        }
        set {
            this.motherNameField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string FatherOccupation {
        get {
            return this.fatherOccupationField;
        }
        set {
            this.fatherOccupationField = value;
        }
    }
    
    /// <remarks/>
    public string MotherOccupation {
        get {
            return this.motherOccupationField;
        }
        set {
            this.motherOccupationField = value;
        }
    }
    
    /// <remarks/>
    public string Nationality {
        get {
            return this.nationalityField;
        }
        set {
            this.nationalityField = value;
        }
    }
    
    /// <remarks/>
    public string Religion {
        get {
            return this.religionField;
        }
        set {
            this.religionField = value;
        }
    }
    
    /// <remarks/>
    public string FatherIncome {
        get {
            return this.fatherIncomeField;
        }
        set {
            this.fatherIncomeField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public int City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public int Distict
    {
        get {
            return this.distictField;
        }
        set {
            this.distictField = value;
        }
    }
    
    /// <remarks/>
    public string PinCode {
        get {
            return this.pinCodeField;
        }
        set {
            this.pinCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ContactNo {
        get {
            return this.contactNoField;
        }
        set {
            this.contactNoField = value;
        }
    }
    
    /// <remarks/>
    public string HostCode {
        get {
            return this.hostCodeField;
        }
        set {
            this.hostCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public int SortSeq {
        get {
            return this.sortSeqField;
        }
        set {
            this.sortSeqField = value;
        }
    }
    
    /// <remarks/>
    public string CreatedDate {
        get {
            return this.createdDateField;
        }
        set {
            this.createdDateField = value;
        }
    }
    
    /// <remarks/>
    public int CreatedBy {
        get {
            return this.createdByField;
        }
        set {
            this.createdByField = value;
        }
    }
    
    /// <remarks/>
    public string ModifiedDate {
        get {
            return this.modifiedDateField;
        }
        set {
            this.modifiedDateField = value;
        }
    }
    
    /// <remarks/>
    public int ModifiedBy {
        get {
            return this.modifiedByField;
        }
        set {
            this.modifiedByField = value;
        }
    }
}
